### ISSUE TITLE
Question: How to get the weather item

### ISSUE THREAD

**Issue by ShrkSoft** [awesomio/Weather.NET#1]
The maximum temperature, minimum temperature, humidity, etc. could be easily obtained.
However, I don't know how to get the contents (description and icon) of the weather item.
Can you tell me?
I'm sorry, my English is not good.

**Comment by ShrkSoft** [comment]
Self solved.

**Comment by sharpgraf** [comment]
Hi !
the name of the icon you can find in the "icon" field  class OneCallModel or CurrrentWeatherModel

```csharp
string iconName = "04d";
string url = "http://openweathermap.org/img/w/{iconName}.png"
```
example url: http://openweathermap.org/img/w/04d.png

then you will need to download and save the image in any convenient way

I hope it will be useful in future
