### ISSUE TITLE
Typo in CurrrentWeatherModel

### ISSUE THREAD

**Issue by dulfe** [awesomio/Weather.NET#12]
There is a TYPO in `CurrrentWeatherModel`, it should be `CurrentWeatherModel` (2 "r"s instead of 3)

**Comment by sharpgraf** [comment]
Hi dulfe !
It is surprising that this has not been noticed until now. I think it can be corrected in next version, these changes are unlikely to really break something. Thanks for the issue!

**Comment by dulfe** [comment]
Thank you... but, Why was it marked as "invalid" (label)?
