### ISSUE TITLE
Communication Problem since 2 days

### ISSUE THREAD

**Issue by getsolved** [awesomio/Weather.NET#2]
Hello,

using Awesomio in my .net App I no longer get any updates from OpenWeatherMapAPI. The requests are answered with "A problem occured". I have this issue since 2 days now.

Best regards
getsolved

**Comment by sharpgraf** [comment]
> Hello,
> 
> using Awesomio in my .net App I no longer get any updates from OpenWeatherMapAPI. The requests are answered with "A problem occured". I have this issue since 2 days now.
> 
> Best regards
> getsolved

Hi! Sorry for the late answer, works for me, looks like temporary api provider issues
can you share the code? Thank !
